services:
  hub:
    image: selenium/hub:2.53.1
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:2.53.1
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

  firefox:
    image: selenium/node-firefox:2.53.1
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444