name: CI/CD Pipeline

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Selenium Grid
        run: docker-compose up -d

      - name: Run Robot Framework Tests in Docker
        run: |
          docker run --network host -e BROWSER=${{ matrix.browser }} kubeamarap/automation_practice:latest

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: output

  merge:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master'
    steps:
      - uses: actions/checkout@v2
      - name: Merge PR
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout master
          git merge ${{ github.event.pull_request.head.ref }}
          git push origin master

  deploy:
    needs: merge
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Production
        run: |
          # Add your deployment steps here
          echo "Deploying to production"

      - name: Run Post-Deployment Tests
        run: |
          docker run --network host -e BROWSER=chrome kubeamarap/automation_practice:latest